version: '2'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: LEMP_nginx
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - LEMP

    mariaDB:
        image: mariadb:latest
        container_name: LEMP_mariaDB
        restart: always
        command: mysqld --innodb-buffer-pool-size=20M
        volumes:
            - ./database:/var/lib/mysql:rw
        ports:
            - "3306:3306"
        depends_on:
            - nginx
        environment:
            - MYSQL_ROOT_PASSWORD=654321          
        networks:
            - LEMP    

    php:
        image: php:7-fpm-alpine
        container_name: LEMP_php
        restart: always
        volumes:
            - ./code:/code
        ports:
            - "9000:9000"       
        depends_on:
            - mariaDB
        links:
            - mariaDB
        networks:
            - LEMP

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: LEMP_phpMyAdmin
        restart: always
        links:
            - mariaDB
        ports:
            - "8183:80"
        environment:        
            PMA_ARBITRARY: 1
        depends_on:
            - mariaDB
        networks:
            - LEMP
    
networks:
    LEMP:
        driver: bridge

